### ISSUE TITLE
x64 bug in extension regex processing causes runaway memory use

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-textmate#56] opened 2017-10-12 08:34 UTC
_From @coe-jeubanks on September 29, 2017 17:38_

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
plsql|cas|0.0.3
jet|dio|0.0.1
xml|Dot|1.9.2
backspace-plusplus|jri|0.0.16
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
SQR|Cit|0.2.5

(1 theme extensions excluded)

---

Extension processing using x64 version of VS Code improperly handles single quote regex match of "('(?:\\\\'|.)*?')" with a string containing a pound sign character (e.g. 'string#'). Symptom is runaway memory use until the workstation becomes unresponsive.

Steps to Reproduce:

1. Install SQR 0.2.5 extension
2. Open a file containing a single line:   print 'Emp# '     (+1,1)

Reproduces without extensions: No

_Copied from original issue: Microsoft/vscode#35391_

**Comment by aeschli** [comment] 2017-10-12 08:34
_From @sandy081 on October 2, 2017 9:30_

Please file bug against the corresponding SQR extension

**Comment by aeschli** [comment] 2017-10-12 08:34
_From @coe-jeubanks on October 2, 2017 15:4_

The bug is not caused by the extension. The bug is caused by faulty regex processing in VS Code. The regex processing works perfectly well in the x86 version of VS Code.

**Comment by aeschli** [comment] 2017-10-12 08:34
@coe-jeubanks Where did you find this regex?

**Comment by aeschli** [comment] 2017-10-12 08:34
Ok, got it: https://github.com/CityOfEscondido/Visual-Studio-Code-SQR/blob/6754ec99c75ae70aaa88d454675f4365eb9401de/syntaxes/sqr.json#L68

**Comment by coe-jeubanks** [comment] 2017-10-12 14:53
Thanks for moving it over here. I didn't know where to file it. I realized that it could possibly be due to a circular reference? In SQR, variables can start with a # or a $, so there is a regex for those situations. Then there is a regex for strings surrounded by either single or double quotes. So if you have a # or $ inside of a quoted string, I'm thinking perhaps the processing gets stuck in an infinite loop trying to process both of the regexes.

**Comment by coe-jeubanks** [comment] 2018-03-19 15:13
@RameshKris found the cause of this. But it only locks up the x64 version of VSCode.

_Using # in the file causes VSC to lock up.
Steps to reproduce. Open a test.sqr file,
type "#"_

Issues seems to be a conflict with

{ "name": "keyword.include.SQR",
"match": "(\s)*(#)(?i:include)\s"
},
{ "name": "storage.type.SQR",
"match": "(\s)*(#)(?i:define)\s"
},

this fixed it.
{ "name": "keyword.include.SQR",
"match": "#(?i:include)\b"
},
{ "name": "storage.type.SQR",
"match": "(#)(?i:define)\b"
},

**Comment by alexandrudima** [comment] 2018-03-20 11:24
This might be due to our usage of an oldish version of oniguruma, which comes from https://github.com/atom/node-oniguruma

**Comment by alexdima** [comment] 2020-10-07 22:24
We are now on the latest and greatest oniguruma.

**Closed by alexdima** 2020-10-07 22:24 UTC
Labels: bug, upstream
