### ISSUE TITLE
JS variables with ternary assignments are incorrectly scoped to entity.name.function

### ISSUE THREAD

**Issue by stephenmirving** [microsoft/vscode-textmate#115] opened 2019-09-27 00:43 UTC
Consider the formatting for the following variable assignment that uses a ternary operator:

```
let result = (
  i % 3 === 0
    ? 'fizz'
    : 'buzz'
);
```

According to TextMate in VSCode, this now falls under entity.name.function.js, though it most certainly is not a function. If you instead format it like this:

```
let result = 
  (i % 3 === 0
    ? 'fizz'
    : 'buzz'
  );
```

it will fall correctly under variable.other.readwrite.js, as it will if it is formatted all the other ways I've tried. Problem is, I like formatting it in way no. 1, but I cannot do so if it then colors all the references as if it were a function. 

It seems that if you make an assignment with var, let, or const and start it with and opening parenthesis `(` after the equal size `=`, and then have a line break immediately following, TextMate will incorrectly assume it is a function assignment, which seems rather odd to me as I haven't ever seen a function written like that.

I would be incredibly pleased if this was fixed, thank you for your time.

**Comment by msftrncs** [comment] 2019-09-27 01:46
@stephenmirving, the source of the problem is actually at https://github.com/Microsoft/TypeScript-TmLanguage/blob/master/TypeScriptReact.tmLanguage.  (I'm pretty sure).  VS Code's JavaScript syntax highlighting is based on (automatically derived from) the one for TypeScript.  I have seen a few of these kinds of issues.

It very much looks like this is deliberate, as if this is possible a notation used to assign a function to a variable (the pattern is called 'function assignment'). 

Also, in your examples, you in no way need the parenthesis, so you might have a hard sell on convincing someone that this needs addressed.

**Comment by msftrncs** [comment] 2019-09-27 01:50
One potential reason for this pattern being deliberate is that TextMate (not just VSCode) has some limitations.  All characters on a line must be scoped only by processing the current line, or from lines before it, so one cannot look to the next line to make a scope choice.  They probably expect ` = (` to be the start of a function assignment, but won't know until a later line if it was in fact.

**Comment by stephenmirving** [comment] 2019-09-27 03:26
> They probably expect = ( to be the start of a function assignment, but won't know until a later line if it was in fact.

So why then does the TM scope only change after a line break on that line? Are 

> Also, in your examples, you in no way need the parenthesis, so you might have a hard sell on convincing someone that this needs addressed.

My example was obviously simplified for the sake of demonstration, but dense ternary operators can be difficult for a lot of people to read, which is why Douglas Crockford recommends wrapping all ternaries in parenthesis and putting `?` and `:` on their own line in his style guide for JavaScript. He writes them the same was a me except he doesn't indent the `?` or `:`. See for yourself here: [https://www.crockford.com/code.html](https://www.crockford.com/code.html). Given how prominent Crockford's books, lessons, and style dictates are in the JavaScript community and how many developer have learned from his work, it seems to me that the TextMate JS syntax coloring shouldn't be telling him and every developer that learned from his style that they are writing ternary operators incorrectly.

There are a lot of conventions we use in code that are not strictly necessary for the compiler but enhance readability for human beings, which is who we actually should be writing our code for.

**Comment by msftrncs** [comment] 2019-09-28 02:15
If you truly have a dense ternary, it probably won't be elegant.  I make tremendous use of ternary in every language I can, they usually get very dense, and I have never found much help for formatting them...

On the topic of why this happens, a function assignment is the exact same format.  (BTW, I have little experience in JS/TS, so I had to look this up.)

```JS
var name = (param:type) { statements; };
// or
var name = (
    param:type
) {
    statements;
};
```

Since the TextMate engine requires the scoping of the line to be determined by the end of the line, the TextMate grammar for TypeScript (and thus JS) assumes that `var name = (` is the function assignment notation, because it cannot look to the next line to make that determination.   If you type it all on one line, it will eventually see `param:` and goes, 'ah ha!' the `:` makes a parameter definition, this must be a function assignment.   However, note that the ':' does not need to be on the same line for the notation to be a valid function assignment, but, at this point, the grammar does not scope it this way, because now it thinks this might just be a normal expression.

**Comment by msftrncs** [comment] 2019-09-28 02:32
@stephenmirving, if you have posted this issue on the TypeScript grammar repository, be sure to link this issue to that one (one side or the other, post the URL to the other in a comment), and then close this one, as there is nothing vscode-textmate can do about this.

Thanks,

**Comment by mjbvz** [comment] 2019-10-24 23:42
Yes this looks like an issue with the grammar itself, not the grammar engine.

Closing as upstream

**Closed by mjbvz** 2019-10-24 23:42 UTC
