### ISSUE TITLE
TextMate grammar does not parse correctly under 1.86

### ISSUE THREAD

**Issue by tinygiant98** [microsoft/vscode-textmate#226] opened 2024-02-06 18:35 UTC
Type: `Bug` (Possible regression)

Steps to reproduce:  Use the extension under 1.86

We have a language server implementation (as an extension) for a custom language that relies on a textMate grammar. Under 1.85 and all previous versions of vsCode, this textmate grammar parses correctly and the language server reliably provided the product it is designed to supply.

When vscode updated to 1.86, the textmate grammar no longer reliably parses and always errors on a line including `</dict>`, though the actual grammar component it errors out on varies considerably. This, and the fact that it worked reliably until 1.86, leads me to believe there was a base code change that caused the issue, not the grammar itself, since the grammar hasn't changed in years. Multiple members of our development team have noted the same behavior on 1.86. Reverting to 1.85 fixes the issue for all team members, and on various OS.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by PhilippeChab** [comment] 2024-02-08 14:56
The issue isn't related to this package, but vscode extension initialization process.

You can close this issue in favor of that [one](https://github.com/microsoft/vscode/issues/204731).

**Closed** 2024-02-09 01:25 UTC
